#!/usr/bin/python3
import time
from listdir import applications
from listdir import ardiff

from launcher import dock 

# import bamf
import os
# import asyncio
# sortcuts=[]
from shortcuts import Content

#test.add("telegramdesktop")
# if "telegramdesktop" in test.ls.dockitems:


test = dock()
# test.remove_from_dock("telegramdesktop")
items_list=[]

while 1:
	
	before = applications()
	# time.sleep(1)
	# print("----", shortc)
	for item in ardiff(before, watch="installed").tolist:
		
		check = Content(item)
		if check.getitem("Type") == "Application":
			
			if not item in before:
				items_list.append(item)


	for item in items_list:
		if item in before:
			
			
			
			time.sleep(5)
			if test.add_toDock(item):
				items_list.remove(item)
				
			time.sleep(1)

			

	
	
	


	
	# Wed Mar  6 18:49:26 CST 2024
	# Thu Mar  7 04:25:23 CST 2024
	# Thu Mar 21 08:27:19 CDT 2024

